Repository orbiternassp/NASSP, pull requests merged in 2021-09, with the labels that each got.

#636 Convective radiators
  Orbitersdk/samples/ProjectApollo/src_sys/PanelSDK/Internals/Hsystems.cpp
  Orbitersdk/samples/ProjectApollo/src_sys/PanelSDK/Internals/Thermal.cpp
Labels: systems

#645 Fix TEL TRUN 25° offset and Apollo 11 G&N PTC checklist
  Doc/Project Apollo - NASSP/Checklists/Apollo 11 Checklists.xls
  Orbitersdk/samples/ProjectApollo/src_csm/CSMcomputer.cpp
Labels: bug, systems, docs/procedures, ignore changelog

#646 SPS location moved back to centerline
  Orbitersdk/samples/ProjectApollo/src_csm/saturn.cpp
  Orbitersdk/samples/ProjectApollo/src_csm/saturn.h
  Orbitersdk/samples/ProjectApollo/src_csm/saturnmesh.cpp
  Orbitersdk/samples/ProjectApollo/src_csm/sps.cpp
  Orbitersdk/samples/ProjectApollo/src_launch/rtcc.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/RTCCSystemParameters.h
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/rtcc_intermediate_library_programs.cpp
  Scenarios/Project Apollo - NASSP/Apollo 10 - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 10 MCC - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 11 - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 11 MCC - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 7 - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 7 MCC - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 8 - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 8 MCC - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 9 - Launch.scn
  Scenarios/Project Apollo - NASSP/Apollo 9 MCC - Launch.scn
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Apollo 12 - Launch.scn
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Apollo 13 - Launch and Landing.scn
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Apollo 13 - Launch.scn
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Apollo 14 - Launch.scn
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Apollo 15 - Launch.scn
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Apollo 16 - Launch.scn
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Apollo 17 - Launch.scn
Labels: enhancement

#649 Correct SM RCS thruster directions; Improve SCS Auto TVC behavior; fi…
  Orbitersdk/samples/ProjectApollo/src_csm/saturn.cpp
  Orbitersdk/samples/ProjectApollo/src_csm/scs.cpp
  Orbitersdk/samples/ProjectApollo/src_csm/scs.h
  Orbitersdk/samples/ProjectApollo/src_sys/nasspdefs.h
Labels: enhancement

#650 Change previous main and hover thruster groups to THGROUP_USER
  Orbitersdk/samples/ProjectApollo/src_csm/saturnmesh.cpp
  Orbitersdk/samples/ProjectApollo/src_launch/rtcc.cpp
  Orbitersdk/samples/ProjectApollo/src_lm/lemmesh.cpp
  Orbitersdk/samples/ProjectApollo/src_saturn/sat1bmesh.cpp
  Orbitersdk/samples/ProjectApollo/src_saturn/sat5mesh.cpp
Labels: enhancement
