Repository orbiternassp/NASSP, pull requests merged in 2022-05, with the labels that each got.

#773 Launch window processor
  Config/ProjectApollo/RTCC/Skylab 2 Constants.txt
  Doc/Project Apollo - NASSP/Programmers Notes/ApolloRTCCMFD.pdf
  Doc/Project Apollo - NASSP/Programmers Notes/ApolloRTCCMFD.tex
  Doc/Project Apollo - NASSP/Programmers Notes/ApolloRTCCMFDFiles/LaunchTargetingDisplay.png
  Missions/ProjectApollo/Apollo 18.cfg
  Orbitersdk/samples/ProjectApollo/Build/VC2017/MCC.vcxproj
  Orbitersdk/samples/ProjectApollo/Build/VC2017/MCC.vcxproj.filters
  Orbitersdk/samples/ProjectApollo/src_launch/rtcc.cpp
  Orbitersdk/samples/ProjectApollo/src_launch/rtcc.h
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ARCore.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ARCore.h
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApolloRTCCMFD.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApolloRTCCMFD.h
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApolloRTCCMFD_Display.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApollomfdButtons.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/GeneralPurposeManeuver.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/LWP.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/LWP.h
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/OrbMech.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/RTCCTables.h
  Orbitersdk/samples/ProjectApollo/src_saturn/LVDC.cpp
  Scenarios/Project Apollo - NASSP/WIP Scenarios/Skylab 2 - Launch.scn
Labels: enhancement

#774 MFD fixes and switch failure function
  Orbitersdk/samples/ProjectApollo/Build/VC2017/ApolloRTCCMFD.vcxproj
  Orbitersdk/samples/ProjectApollo/Build/VC2017/ApolloRTCCMFD.vcxproj.filters
  Orbitersdk/samples/ProjectApollo/Build/VC2017/ProjectApolloMFD.vcxproj
  Orbitersdk/samples/ProjectApollo/Build/VC2017/ProjectApolloMFD.vcxproj.filters
  Orbitersdk/samples/ProjectApollo/src_aux/nassputils.h
  Orbitersdk/samples/ProjectApollo/src_mfd/ProjectApolloMFD.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ARCore.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ARCore.h
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApolloRTCCMFD.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApolloRTCCMFD.h
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApolloRTCCMFD_Display.cpp
  Orbitersdk/samples/ProjectApollo/src_rtccmfd/ApollomfdButtons.cpp
  Orbitersdk/samples/ProjectApollo/src_sys/toggleswitch.cpp
  Orbitersdk/samples/ProjectApollo/src_sys/toggleswitch.h
Labels: enhancement, systems

#782 Apollo 8 MCC: entry REFSMMAT uplink based on nominal trajectory, not …
  Orbitersdk/samples/ProjectApollo/src_launch/RTCC_Mission_C_PRIME.cpp
  Scenarios/Project Apollo - NASSP/Apollo - Mission Scenarios/Apollo 8/Apollo 8 - 10 - Before TEI TIG-15min.scn
Labels: ignore changelog, RTCC/MCC

#784 Add "MCC Scrubbed" procedures and proper uplinks to Apollo 8 checklists
  Doc/Project Apollo - NASSP/Checklists/Apollo 8 Checklists.xls
Labels: docs/procedures, ignore changelog, RTCC/MCC
