Repository orbiternassp/NASSP, pull requests merged in 2024-01, with the labels that each got.

#1133 Make the LM visible in the CSM optics from up to 400nm
  Orbitersdk/samples/ProjectApollo/src_lm/LEM.cpp
  Orbitersdk/samples/ProjectApollo/src_lm/LEM.h
  Orbitersdk/samples/ProjectApollo/src_lm/lemmesh.cpp
  Orbitersdk/samples/ProjectApollo/src_saturn/sivb.cpp
  Orbitersdk/samples/ProjectApollo/src_saturn/sivb.h
Labels: enhancement, Orbiter's fault

#1148 fix missing n2 blanket in fc creation
  Config/ProjectApollo/SaturnSystems.cfg
Labels: bug

#1162 Fix a small timewarp related VC free cam bug
  Orbitersdk/samples/ProjectApollo/src_csm/saturnvc.cpp
  Orbitersdk/samples/ProjectApollo/src_lm/lemvc.cpp
Labels: bug, ignore changelog
